# Generated by Django 2.2 on 2021-06-17 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('num_equipo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(default='', max_length=100)),
                ('tipo_equipo', models.CharField(choices=[('tractor', 'TRACTOR'), ('arado', 'ARADO'), ('rastra', 'RASTRA'), ('pulverizadora', 'PULVERIZADORA'), ('cosechadora', 'COSECHADORA'), ('otros', 'OTROS')], max_length=20, null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('marca', models.CharField(default='', max_length=20)),
                ('modelo', models.CharField(default='', max_length=20)),
                ('año', models.PositiveSmallIntegerField(default=1993)),
                ('estado_equipo', models.CharField(choices=[('malo', 'Malo'), ('regular', 'Regular'), ('buena', 'Buena'), ('excelente', 'Excelente')], max_length=10)),
                ('para_que', models.CharField(choices=[('venta', 'Venta'), ('renta', 'Renta'), ('ambos', 'Ambos')], max_length=10)),
                ('precio_venta', models.FloatField(null=True)),
                ('precio_renta_dia', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('apartado', 'Apartado'), ('rentado', 'Rentado'), ('inactivo', 'Inactivo'), ('eliminado', 'Eliminado')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaccion', models.CharField(max_length=10)),
                ('estatus', models.CharField(choices=[('1', 'Completada'), ('2', 'Abortada'), ('3', 'En Ejecucuón')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Arado',
            fields=[
                ('id_equipo', models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tes2.Equipo')),
                ('tipo', models.CharField(max_length=20)),
                ('reversible', models.BooleanField(default=False)),
                ('no_cuerpos', models.PositiveSmallIntegerField(max_length=3)),
                ('neumatica_mecanica', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cosechadora',
            fields=[
                ('id_equipo', models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tes2.Equipo')),
                ('tipo_cultivo', models.CharField(max_length=20)),
                ('potencia', models.PositiveSmallIntegerField(max_length=4)),
                ('capacidad_granos', models.PositiveSmallIntegerField(null=True)),
                ('tasa_descarga', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Otros_equipos',
            fields=[
                ('id_equipo', models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tes2.Equipo')),
                ('potencia', models.PositiveSmallIntegerField(null=True)),
                ('producto_agricola', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pulverizadora',
            fields=[
                ('id_equipo', models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tes2.Equipo')),
                ('autopropulsada', models.BooleanField(default=False)),
                ('tamaño_tanque', models.PositiveSmallIntegerField()),
                ('no_boquillas', models.PositiveSmallIntegerField(max_length=3)),
                ('capacidad_bomba', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rastra',
            fields=[
                ('id_equipo', models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tes2.Equipo')),
                ('acople', models.CharField(max_length=20)),
                ('tipo_cuerpo', models.CharField(max_length=20)),
                ('no_cuerpos', models.PositiveSmallIntegerField(max_length=3)),
                ('disposicion_cuerpos', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sembradora',
            fields=[
                ('id_equipo', models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tes2.Equipo')),
                ('tipo', models.CharField(max_length=20)),
                ('fertilizadora', models.BooleanField(default=False)),
                ('no_tolvas', models.PositiveSmallIntegerField(max_length=3)),
                ('neumatica_mecanica', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id_equipo', models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tes2.Equipo')),
                ('potencia', models.CharField(max_length=4)),
                ('estrias_PTO', models.CharField(max_length=2)),
                ('enganche_tres_puntos', models.BooleanField()),
                ('traccion', models.CharField(max_length=9)),
                ('cabina', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(auto_now=True)),
                ('importe_total', models.FloatField()),
                ('id_transaccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tes2.Transaccion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('apellido_1', models.CharField(max_length=30, null=True)),
                ('apellido_2', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(max_length=20)),
                ('nivel_permisos', models.PositiveSmallIntegerField(default=1)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('id_usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=40)),
                ('coord_x', models.CharField(max_length=20)),
                ('coord_y', models.CharField(max_length=20)),
                ('referencias', models.CharField(max_length=200)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tes2.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='transaccion',
            name='desde_donde',
            field=models.ForeignKey(default='0001', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='desde_donde_ubicacion', to='tes2.Ubicacion'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='hacia_donde',
            field=models.ForeignKey(default='0002', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='hacia_donde_ubicacion', to='tes2.Ubicacion'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='id_arrendatario',
            field=models.ForeignKey(default='0001', on_delete=django.db.models.deletion.SET_DEFAULT, to='tes2.Usuario'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='id_equipo',
            field=models.ForeignKey(default='0001', on_delete=django.db.models.deletion.SET_DEFAULT, to='tes2.Equipo'),
        ),
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now=True)),
                ('tiempo_renta', models.SmallIntegerField()),
                ('importe_total', models.FloatField()),
                ('id_transaccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tes2.Transaccion')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='donde_esta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tes2.Ubicacion'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='id_dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
