# Generated by Django 2.2 on 2021-06-20 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arado',
            name='no_cuerpos',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cosechadora',
            name='potencia',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.CharField(choices=[('tractor', 'TRACTOR'), ('arado', 'ARADO'), ('rastra', 'RASTRA'), ('sembradora', 'SEMBRADORA'), ('pulverizadora', 'PULVERIZADORA'), ('cosechadora', 'COSECHADORA'), ('otros', 'OTROS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pulverizadora',
            name='no_boquillas',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='rastra',
            name='no_cuerpos',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sembradora',
            name='no_tolvas',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='')),
                ('es_principal', models.BooleanField(default=False)),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tes2.Equipo')),
            ],
        ),
    ]
