# Generated by Django 2.2 on 2021-06-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0002_auto_20210620_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
