# Generated by Django 2.2 on 2021-06-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0003_auto_20210621_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
