# Generated by Django 2.2 on 2022-01-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0004_auto_20220126_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estatus',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
