# Generated by Django 2.2 on 2021-06-23 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0004_auto_20210621_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id_transaccion',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='Fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha_inicial',
            field=models.DateField(default='2021-06-22'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='id_dueño',
            field=models.ForeignKey(default='0001', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dueño_usuario', to='tes2.Usuario'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='importe_total',
            field=models.FloatField(default=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id_arrendatario',
            field=models.ForeignKey(default='0001', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='arrendatario_usuario', to='tes2.Usuario'),
        ),
        migrations.DeleteModel(
            name='Renta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
