# Generated by Django 2.2 on 2022-01-29 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0005_auto_20220126_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='quien_manda',
        ),
        migrations.AddField(
            model_name='conversacion',
            name='id_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tes2.Solicitud'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='aceptada_dueño',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='aceptada_solicitante',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
