# Generated by Django 2.2 on 2021-06-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0005_auto_20210622_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='estado',
            field=models.CharField(default='México', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='municipio',
            field=models.CharField(default='Texcoco', max_length=30),
            preserve_default=False,
        ),
    ]
