# Generated by Django 2.2 on 2021-06-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0006_auto_20210622_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='Fecha_final',
            new_name='fecha_final',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tipo_transaccion',
            field=models.CharField(default='renta', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='estado',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='municipio',
            field=models.CharField(max_length=100),
        ),
    ]
