# Generated by Django 2.2 on 2021-06-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0007_auto_20210628_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='id',
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id_transaccion',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
