# Generated by Django 2.2 on 2021-07-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0008_auto_20210628_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('visto', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(default='0001', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='destinatario_usu', to='tes2.Usuario')),
                ('id_transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tes2.Transaccion')),
                ('remitente', models.ForeignKey(default='0001', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='remitente_usu', to='tes2.Usuario')),
            ],
        ),
    ]
