# Generated by Django 2.2 on 2021-07-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0009_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='estatus',
            field=models.CharField(choices=[('1', 'Completada'), ('2', 'Abortada'), ('3', 'En Ejecución')], max_length=12),
        ),
    ]
