# Generated by Django 2.2 on 2021-07-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0010_auto_20210706_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='contestado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estatus',
            field=models.CharField(choices=[('1', 'Completada'), ('2', 'Abortada'), ('3', 'En Ejecución'), ('4', 'En espera')], max_length=12),
        ),
    ]
