# Generated by Django 2.2 on 2021-07-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0011_auto_20210707_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
