# Generated by Django 2.2 on 2021-08-10 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tes2', '0012_ubicacion_eliminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='estatus',
            field=models.CharField(choices=[('1', 'Completada'), ('2', 'Abortada'), ('3', 'En Ejecución'), ('4', 'En Espera')], max_length=12),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_equipo', models.CharField(choices=[('tractor', 'TRACTOR'), ('arado', 'ARADO'), ('rastra', 'RASTRA'), ('sembradora', 'SEMBRADORA'), ('pulverizadora', 'PULVERIZADORA'), ('cosechadora', 'COSECHADORA'), ('otros', 'OTROS')], max_length=12)),
                ('param_1', models.CharField(max_length=50)),
                ('param_2', models.CharField(max_length=50)),
                ('param_3', models.CharField(max_length=50)),
                ('param_4', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=255)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('completada', models.BooleanField(default=False)),
                ('id_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
