# Generated by Django 2.2 on 2021-12-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0016_auto_20211207_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='tipo_operacion',
            field=models.CharField(default='renta', max_length=5),
            preserve_default=False,
        ),
    ]
