# Generated by Django 2.2 on 2021-12-08 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0017_solicitud_tipo_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='a_donde',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='tes2.Ubicacion'),
        ),
    ]
