# Generated by Django 2.2 on 2021-12-08 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0018_solicitud_a_donde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='id_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tes2.Usuario'),
        ),
    ]
