# Generated by Django 2.2 on 2021-12-08 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0019_auto_20211207_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='id_dueño_eq',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='sol_dueño', to='tes2.Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sol_sol', to='tes2.Usuario'),
        ),
    ]
