# Generated by Django 2.2 on 2021-12-08 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0020_auto_20211207_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='desde_donde',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dsde_donde_sol', to='tes2.Ubicacion'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='a_donde',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='hacia_donde_sol', to='tes2.Ubicacion'),
        ),
    ]
