# Generated by Django 2.2 on 2021-12-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0021_auto_20211208_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='comentario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
