# Generated by Django 2.2 on 2021-12-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0022_auto_20211208_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
    ]
