# Generated by Django 2.2 on 2021-12-09 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0024_auto_20211208_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='usuario_1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='usr_1_convo', to='tes2.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversacion',
            name='usuario_2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='usr_2_convo', to='tes2.Usuario'),
            preserve_default=False,
        ),
    ]
