# Generated by Django 2.2 on 2021-12-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0025_auto_20211209_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='ubicacion_base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubcacion_base', to='tes2.Ubicacion'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='donde_esta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donde_esta', to='tes2.Ubicacion'),
        ),
    ]
