# Generated by Django 2.2 on 2022-01-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0026_auto_20211222_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='coord_x',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='coord_y',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
