# Generated by Django 2.2 on 2022-01-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0028_auto_20220106_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='coord_x',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='coord_y',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='estado',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='municipio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
