# Generated by Django 2.2 on 2022-01-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes2', '0030_auto_20220107_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='tipo_solicitud',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='area',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
